# -*- coding: utf-8 -*-
"""
Created on Tue Sep 25 14:46:48 2018

@author: Masih
To modify the Ped and Map files generated by Plink to be used by Haploview LD plotter
"""
def LDplotHelper(infile,out):
        #1) convert gender to male in .ped file 
        #Changing the sex in .ped file to male
        txt=open(out+'.ped','w')
        with open (infile+'.ped') as file:
          line=file.readline()
          while line:
                line=line.split(' ')
                line[4]='1'
                line[5]='0'
                txt.write(' '.join(line))
                line=file.readline()
        txt.close()
        
        
        #2) Conver map file to 2-column 'marker\tposition' format as 'Marker Information File'
        txt=open(out+'.map','w')
        with open(infile+'.map','r') as file:
            line=file.readline()
            while line:
                line=line.split('\t')
                line=[line[1],line[3]]
                line='\t'.join(line)
                txt.write(line)
                line=file.readline()
        txt.close()
        
from optparse import OptionParser
import os,sys
parser = OptionParser()
parser.add_option('-I','--infile', dest='infile',help= 'Absolute path to the input Ped/map file [required]')
parser.add_option('-O','--out', dest='out',help='Absolute path to the output Ped/map file [required]')

(options,args)=parser.parse_args()
infile=options.infile
out=options.out


if infile==True and out==True:
	print ("\nModifying the format of Ped and Map file for LDPlotter\n")
	parser.print_help()
	sys.exit(1)
if (infile==None or out==None) :
	print ('\nModifying the format of Ped and Map file for LDPlotter \nRequired filed(s) not supplied\n')
	parser.print_help()
	sys.exit(1)
import ast
input_option_dict=ast.literal_eval(options.__str__())
print ('Entered arguments are...')
for one in input_option_dict:
	print (one,input_option_dict[one])
print ('')

LDplotHelper(infile,out)
