# -*- coding: utf-8 -*-
"""
Created on Tue Sep 25 14:46:48 2018

@author: Masih
To modify the Ped and Map files generated by Plink to be used by Haploview LD plotter
"""

infile = str(snakemake.input.vcfmap)[:-4]
outfile = str(snakemake.output.haploview_inped)[:-4]

# 1) convert gender to male in .ped file
# Changing the sex in .ped file to male
txt = open(outfile + '.ped', 'w')
with open(infile + '.ped') as file:
    line = file.readline()
    while line:
        line = line.split(' ')
        line[4] = '1'
        line[5] = '0'
        txt.write(' '.join(line))
        line = file.readline()
txt.close()


# 2) Conver map file to 2-column 'marker\tposition' format as 'Marker Information File'
txt = open(outfile + '.map', 'w')
with open(infile + '.map', 'r') as file:
    line = file.readline()
    while line:
        line = line.split('\t')
        line = [line[1], line[3]]
        line = '\t'.join(line)
        txt.write(line)
        line = file.readline()
txt.close()
