#output directory name
outputDIR: BACGWASIM_quant_s100_m0.05_r0.01


#BacGWASim dependencies not provided by conda channels
simbac_path: dependencies/sim/SimBac/SimBac
haploview: dependencies/ld/Haploview.jar
gcta: dependencies/gcta/gcta_1.93.2beta/gcta64


#Genome simulation parameters
num_species: 200                 #Number of samples in the simulated population
genome_length: 20000             #Length of the genome (.bp)
mutation_rate: 0.06              #Mutation rate
r_i: 0.01                        #Recombination rate
random_seed: 1487                #Random seed for reproducibility of results
maf: 0.01                        #Minor allele frequency threshold of rare alleles to be discarded
varNumber: -1                    #Number of simulated variants, if kept '-1', variant number will be solely a function of mutation rate


#Phenotype simulation parameters
phenType: quant                  #Type of simulated phenotype,'cc':binary case-control, 'quant': quantitative
causalMAF: 0.1                   #Minimum MinorAlleleFrequency of causal markers
causalMaxMAF: 0.4                #Maximum MinorAlleleFrequency of causal markers
causalMaxLD: 0.6                 #Maximum permitted r2 score between pairs of causal markers in window size of 1000 candidate causal markers meeting causalMAF and causalMaxMaf thresholds
causal_variant_Num: 16           #Number of causal markers
effect_size_ODR: 2,3,4,7,10,11,15,20    #Effect sizes of causal markers (.odds ratios) (comma separated,Must be a multiple of causal_variant_Num)
phenReplication: 10              #Number of phenotype replication sets
heritability: 1    #Heritability of phenotype
diseasePrevalence: 0.5           #Prevalence of phenotype
#in case of case-control binary phenotype simulation, number of case and control samples must be defined by 'case' and 'control' parameters
case: 50
control: 50

#Linkage Disequilibrium plotting
snplimit: 3000                   #Number of SNPs randomly selected for plotting linkage map (Increasing this number will significatnly increase computation time and require increasing the java heap size
heapSize: 1000                   #java heap_size for ld plot visualization (.mb)
ldmaf: 0.1                       #Minimum MinorAlleleFrequency of markers for LD plotting (Lower this values, it is more difficult to estiamte accurate r2 values between pairs of markers leading to more noisy plot)