#Define the following pathes 
#output directory name
outputDIR: BACGWASIM_1000_m0.01_r0.05
cpus: 32

#number of species to be simulated
num_species: 1000
genome_length: 2000000


#input parameters
#simbac
mutation_rate: 0.01
r_i: 0.05
r_e: 0.00
random_seed: 1487

#Dependecies
simbac_path: dependencies/sim/SimBac/SimBac
haploview: dependencies/ld/Haploview.jar

#Phenotype simulation parameters
phenType: cc   #'cc':binary case-control, 'quant': quantitative
causalMAF: 0.2
causalMaxLD: 0.6  #Maximum permitted r2 score between pairs of causal markers in window size of 1000 markers
effect_size_ODR: 2,3,4,7,10,11,15,20 
causal_variant_Num: 16
phenReplication: 10
heritability: 1
diseasePrevalence: 0.5
#in case of case-control binary phenotype simulation
case: 500
control: 500

#Linkage Disequilibrium plotting
snplimit: 3000 #Number of SNPs randomly selected for plotting linkage map
ldmaf: 0.2