name: BacGWASim
channels:
  - defaults
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - pandas==1.1.5
  - pyvcf==0.6.8
  - scipy==1.5.2
  - numpy==1.19.2
  - matplotlib>=3.4
  - snakemake==5.31.1
  - snp-sites==2.5.1
  - bcftools==1.10.2
  - plink==1.90b6.18
  - gcta==1.93.2beta
  - simbac==0.1a
  - dendropy