# Output directory name
output_dir: BACGWASIM_quant_s100_m0.05_r0.01


# BacGWASim dependencies not provided by conda channels
simbac_path: dependencies/sim/SimBac/SimBac
haploview: dependencies/ld/Haploview.jar
gcta: dependencies/gcta/gcta_1.93.2beta/gcta64


# Genome simulation parameters
num_species: 200      # Number of samples in the simulated population
genome_length: 20000  # Length of the genome (.bp)
mutation_rate: 0.06   # Mutation rate
recomb_rate: 0.01     # Recombination rate
maf: 0.01             # Minor allele frequency threshold of rare alleles to be discarded
num_var: -1           # Number of simulated variants, if kept '-1', variant number will be solely a function of mutation rate
random_seed: 1487     # Random seed for reproducibility of results

# Phenotype simulation parameters
phen_type: quant                      # Type of simulated phenotype,'cc':binary case-control, 'quant': quantitative
num_causal_var: 16                    # Number of causal markers
causal_maf_min: 0.1                   # Minimum MinorAlleleFrequency of causal markers
causal_maf_max: 0.4                   # Maximum MinorAlleleFrequency of causal markers
causal_ld_max: 0.6                    # Maximum permitted r2 score between pairs of causal markers in window size of 1000 candidate causal markers meeting causalMAF and causalMaxMaf thresholds
effect_size_odr: 2,3,4,7,10,11,15,20  # Effect sizes of causal markers (.odds ratios) (comma separated,Must be a multiple of causal_variant_Num)
phen_replication: 10                  # Number of phenotype replication sets
heritability: 1                       # Heritability of phenotype
disease_prevalence: 0.5               # Prevalence of phenotype
case: 50                              # In case of case-control binary phenotype simulation, number of case and control samples must be defined by 'case' and 'control' parameters
control: 50

# Linkage Disequilibrium plotting
snp_limit: 3000  # Number of SNPs randomly selected for plotting linkage map (Increasing this number will significatnly increase computation time and require increasing the java heap size
heap_size: 1000  # Java heap_size for ld plot visualization (.mb)
ld_maf: 0.1      # Minimum MinorAlleleFrequency of markers for LD plotting (Lower this values, it is more difficult to estiamte accurate r2 values between pairs of markers leading to more noisy plot)