import os

def plot_ld(wildcards):
    plot = [
        "{outputDIR}/simulations/ld/ld_plot.png".format(outputDIR=config["output_dir"]),
        "{outputDIR}/simulations/ld/ld_stackplot.png".format(outputDIR=config["output_dir"]),
    ]
    
    if config["plot_ld"]:
        return plot
    else:
        return []


rule all:
    input:
        expand("{outputDIR}/simulations/phenSim/{replication_index}/sim{replication_index}.png",outputDIR=config["output_dir"],replication_index=range(config['phen_replication'])),
        expand("{outputDIR}/simulations/genSim/sims.pickle",outputDIR=config["output_dir"]),
        plot_ld


#step1) genome simulator
include: os.path.join('modules','genSim','genSim.smk')

#step2) variant caller
include: os.path.join('modules','varCall','snpSites.smk')
include: os.path.join('modules','varCall','vcfRefiner.smk')

#step3) phenotype simulator
include: os.path.join('modules','phenSim','phenPermutor.smk')
include: os.path.join('modules','phenSim','phenSim.smk')

#step 4) LD visualization
include: os.path.join('modules','ld','ldPlotter.smk')

#step 5) Population structure visualization
include: os.path.join('modules','visualizers','simVis.smk')
