# -*- coding: utf-8 -*-
"""
Created on Tue Sep 25 14:46:48 2018

@author: Masih
To modify the Ped and Map files generated by Plink to be used by Haploview LD plotter
"""
def LDplotHelper(PedInput,MapInput,PedOutput,MapOutput):
        #1) convert gender to male in .ped file 
        #Changing the sex in .ped file to male
        txt=open(PedInput+'.ped','r')
        lines=txt.readlines()
        txt.close()
        txt=open(PedOutput,'w')
        for line in lines:
                line=line.split('\t')
                line[4]='1'
                line[5]='0'
                line='\t'.join(line)
                txt.write(line)
        txt.close()
        
        
        #2) Conver map file to 2-column 'marker\tposition' format as 'Marker Information File'
        txt=open(MapOutput,'w')
        with open(MapInput+'.map','r') as file:
            line=file.readline()
            while line:
                line=line.split('\t')
                line=[line[1],line[3]]
                line='\t'.join(line)
                txt.write(line)
                line=file.readline()
        txt.close()
        
from optparse import OptionParser
import os,sys
parser = OptionParser()
parser.add_option('-P','--PedInput', dest='PedInput',help= 'Absolute path to the input Ped file [required]')
parser.add_option('-M','--MapInput', dest='MapInput',help= 'Absolute path to the input Map file [required]')
parser.add_option('-Q','--PedOutput', dest='PedOutput',help='Absolute path to the output Ped file [required]')
parser.add_option('-R','--MapOutput', dest='MapOutput',help= 'Absolute path to the output Map file[required]')

(options,args)=parser.parse_args()
PedInput=options.PedInput
MapInput=options.MapInput
PedOutput=options.PedOutput
MapOutput=options.MapOutput


if PedInput==True and MapInput==True and PedOutput==True and MapOutput==True:
	print ("\nModifying the format of Ped and Map file for LDPlotter\n")
	parser.print_help()
	sys.exit(1)
if (PedInput==None or MapInput==None or PedOutput==None or MapOutput==None) :
	print ('\nModifying the format of Ped and Map file for LDPlotter \nRequired filed(s) not supplied\n')
	parser.print_help()
	sys.exit(1)
import ast
input_option_dict=ast.literal_eval(options.__str__())
print ('Entered arguments are...')
for one in input_option_dict:
	print (one,input_option_dict[one])
print ('')

LDplotHelper(PedInput,MapInput,PedOutput,MapOutput)
