# -*- coding: utf-8 -*-
"""
Created on Tue Sep 25 14:46:48 2018

@author: Masih
To modify the Ped and Map files generated by Plink to be used by Haploview LD plotter
"""
import numpy as np 

def LDplotHelper1(VCFMap,VCFSubset):
        Markers=[]
        with open(VCFMap,'r') as file:
            line=file.readline()
            while line:
                line=line.split('\t')
                Markers.append(line[1])
                line=file.readline()
        if len(Markers)>3000:
            Markers=np.random.choice(Markers,3000,replace=False)
        txt=open(VCFSubset,'w')
        for marker in Markers:
            txt.write(marker+'\n')
        txt.close()
        
from optparse import OptionParser
import os,sys
parser = OptionParser()
parser.add_option('-M','--VCFMap', dest='VCFMap',help= 'Absolute path to the VCFMap file [required]')
parser.add_option('-S','--VCFSubset', dest='VCFSubset',help= 'Absolute path to VCFSubset output [required]')


(options,args)=parser.parse_args()
VCFMap=options.VCFMap
VCFSubset=options.VCFSubset



if VCFMap==True and VCFSubset==True :
	print ("\nTo modify the Ped and Map files generated by Plink to be used by Haploview LD plotter\n")
	parser.print_help()
	sys.exit(1)

import ast
input_option_dict=ast.literal_eval(options.__str__())
print ('Entered arguments are...')
for one in input_option_dict:
	print (one,input_option_dict[one])
print ('')

LDplotHelper1(VCFMap,VCFSubset)
